config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  get 'bookings/show'
  get 'flights/index'
 
  resources :flights, only: %i[index]
  resources :bookings, only: %i[new create show]
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
    default_scope { order(:code) }

    validates :code, presence: true, length: { is: 3 }
  
    has_many :departure_flights, class_name: 'Flight', foreign_key: 'departure_airport_id', inverse_of: :departure_airport
    has_many :arrival_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id', inverse_of: :arrival_airport
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  default_scope { where('departure_time > ?', DateTime.current).order(:departure_time) }

  validates :departure_time, presence: true
  validates :duration_in_min, presence: true, length: { minimum: 1 }

  belongs_to :departure_airport, class_name: 'Airport', inverse_of: :departure_flights
  belongs_to :arrival_airport, class_name: 'Airport', inverse_of: :arrival_flights 

  has_many :bookings

  def self.search(params)
    target_date = array_to_date(params['time(2i)'], params['time(3i)'], params['time(1i)'])

    Flight.where(
      arrival_airport_id: params[:arrival_airport_id],
      departure_airport_id: params[:departure_airport_id],
      departure_time: (target_date.beginning_of_day..target_date.end_of_day)
    )
  end

  def self.array_to_date(month, day, year)
    DateTime.new(year.to_i, month.to_i, day.to_i)
  end

  def departure_date
    departure_time.strftime('%B %d, %Y')
  end

  def departure_hour
    departure_time.strftime('%I:%M %p')
  end

  def arrival_hour
    (departure_time + duration_in_min.minutes).strftime('%I:%M %p')
  end

  def duration_in_words
    "#{duration_in_min / 60} hr #{duration_in_min % 60} min"
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(allowed_post_params)
    if @booking.save      
      PassengerMailer.with(booking_id: @booking.id).welcome_email.deliver_now
      redirect_to @booking, notice: 'Your flight was successfully booked! A confirmation email has been sent to each passenger.'        
    else
      render :new, status: :unprocessable_entity
    end
  end

  private 
  
  def allowed_post_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    if params && all_search_params_present_and_not_empty? && given_valid_date? && given_upcoming_date? && !same_airports?
      @flights = Flight.search(params)
    elsif params[:searching]
      if !all_search_params_present_and_not_empty?
        flash.now.alert = "All fields in the search form are required."
      elsif !given_upcoming_date?
        flash.now.alert = "This date has already passed."
      elsif !given_valid_date?
        flash.now.alert = "Invalid date."
      elsif same_airports?
        flash.now.alert = "The departure and arrival airports cannot be the same."
      end
    end
  end

  private

  def all_search_params_present_and_not_empty?
    [:departure_airport_id, :arrival_airport_id, :ticket_num, "time(2i)", "time(3i)", "time(1i)"].all? do |key|
      params.has_key?(key) && !params[key].empty?
    end
  end

  def given_valid_date?
    begin
      Flight.array_to_date(params['time(2i)'], params['time(3i)'], params['time(1i)'])
    rescue ArgumentError
      return false
    end
  end

  def given_upcoming_date?
    Flight.array_to_date(params['time(2i)'], params['time(3i)'], params['time(1i)']) >= Date.today
  end

  def same_airports?
    params[:departure_airport_id] == params[:arrival_airport_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_booking_header.html.erb
<div class="text-center">
<h4>Booking for flight from <%= flight.departure_airport.code %> to <%= flight.arrival_airport.code %> </h4>
<h6 class="fw-light"><%= flight.departure_date %> | <%= flight.departure_hour %> - <%= flight.arrival_hour %></h6>
</div>

app/views/bookings/new.html.erb
<div class="alert-container mt-1 mx-1"> 
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>

<div class="booking-card p-3 my-2 card mx-auto mt-5 mb-1">
  <% if params[:flight_id] %>
    <%= render "booking_header", :flight => Flight.find(params[:flight_id]) %>
  <% end %>

  <%= form_with model: @booking, class: "d-flex flex-column" do |booking_form| %>
    <%= booking_form.hidden_field :flight_id, value: params[:flight_id] %>
    <% params[:ticket_num].to_i.times do |i| %>
      <div class="m-2 fw-bold">
        <%= "Passenger #{i+1}" %>
        <%= booking_form.fields_for :passengers, @booking.passengers.build do |passenger_form| %>
          <%= passenger_form.label :name, hidden: true, class: "form-label" %>
          <%= passenger_form.text_field :name, placeholder: "Name", class: "form-control my-3", required: true %>
          <%= passenger_form.label :email, hidden: true, class: "form-label" %>
          <%= passenger_form.email_field :email, placeholder: "Email", class: "form-control my-3", required: true %>
        <% end %>
      </div>
    <% end %>
    <%= booking_form.submit "Confirm booking", class: "btn btn-success ml-1 flex-basis-1 m-2" %>
  <% end %>
</div>

<div class="text-center">
  <%= link_to "Back to flights", :back %>
</div>

app/views/bookings/show.html.erb
<div class="alert-container mt-1 mx-1"> 
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
</div>

<div class="booking-card p-3 my-2 card mx-auto mt-5 mb-1">

  <%= render "booking_header", :flight => @booking.flight %>

  <div>
    <% @booking.passengers.each_with_index do |passenger, i| %>
      <div class="m-2">
        <div class="my-3 fw-bold"><%= "Passenger #{i + 1}" %></div>
        <div class="my-3"><%= "Name: #{passenger.name}" %></div>
        <div class="my-3"><%= "Email: #{passenger.email}" %></div>
      </div>
    <% end %>
  </div>
</div>

<div class="text-center">
  <%= link_to "Search for more flights", flights_path%>
</div>

app/views/flights/index.html.erb
<div class="alert-container mt-1 mx-1"> 
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>

<div class="d-flex justify-content-center align-items-center mb-5">
  <div class="d-flex justify-content-around container-lg flex-column flex-md-row py-0 align-items-center"> 
    <div class="headers">
    <h1 class="text-center text-danger">OdinFlights</h1>     
    <%= form_with url: @flights_path, method: :get, class: "gap-2 d-flex flex-column container-xs select-form flex-shrink-0" do |f| %>

      <div class="align-self-center mt-4">
        <%= f.label :departure_airport_id, hidden: true, class: "form-label" %>
        <%= f.collection_select :departure_airport_id, Airport.all, :id, :code, required: true, autofocus: true, autocomplete: "departure airport", prompt: "From", class: "form-select m-1 bg-primary" %>

        <%= f.label :arrival_airport_id, hidden: true, class: "form-label" %>
        <%= f.collection_select :arrival_airport_id, Airport.all, :id, :code, required: true, autofocus: true, autocomplete: "departure airport", prompt: "To", class: "form-select" %>

        <%= f.label :ticket_num, hidden: true, class: "form-label" %>
        <%= f.select :ticket_num, (1..4), required: true, autofocus: true, autocomplete: "tickets", prompt: "Passengers", class: "form-select" %>

        <%= f.label :time, hidden: true, class: "form-label" %>
        <%= f.date_select :time, required: true, autofocus: true, autocomplete: "time", start_year: Date.today.year, end_year: Date.today.year + 1, use_short_month: true, prompt: { day: 'Day', month: 'Month', year: 'Year' }, order: [:month, :day, :year], class: "form-select" %>

        <%= hidden_field_tag :searching, true %>
      </div>
      <%= f.submit "Search", class: "btn btn-primary mx-4 px-2" %>
    <% end %>
     </div>
  </div>
</div>

<div class="">
  <% if @flights && !@flights.empty? %>
    <div class="text-center">
      <h4>Outbound flights from <%= @flights.first.departure_airport.code %> to <%= @flights.first.arrival_airport.code %></h4>
      <h6 class="fw-light"><%= @flights.first.departure_date %></h6>
    </div>
    <%= form_with model: @booking, url: new_booking_path, method: :get, class: "d-flex flex-column align-items-center" do |f| %>
      <%= hidden_field_tag :ticket_num, params[:ticket_num] %>
      <% @flights.each do |flight| %>
        <div class="d-flex justify-content-center align-items-center flex-basis-1">
          <%= f.radio_button :flight_id, flight.id, class: "form-check-input", required: true %>
          <div class="text-center d-flex justify-content-between container-sm p-3 flight-card rounded m-3 bg-success text-white">
            <div>
              <div><%= flight.departure_hour %></div>
              <div><%= flight.departure_airport.code %></div>
            </div>
            <div>
              <div>Nonstop</div>
              <div><%= flight.duration_in_words %></div>
            </div>
            <div>
              <div><%= flight.arrival_hour %></div>
              <div><%= flight.arrival_airport.code %></div>
            </div>
          </div>
        </div>
      <% end %>
      <%= f.submit "Book flight", class: "btn btn-warning text-dark booking-btn ml-1 mb-5" %>
    <% end %>
  <% elsif params[:searching] %>
    <p class="text-info text-center">No available flights.</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>